"""avatars and brand

Revision ID: 60bcd01a24d9
Revises: cb993ffd1bd9
Create Date: 2026-08-23 13:16:40.615449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60bcd01a24d9'
down_revision: Union[str, Sequence[str], None] = 'cb993ffd1bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_kind', sa.String(length=20), nullable=False, server_default='initials'))
    op.add_column('users', sa.Column('avatar_value', sa.String(length=500), nullable=True))
    op.add_column('workspaces', sa.Column('brand_kind', sa.String(length=20), nullable=False, server_default='initials'))
    op.add_column('workspaces', sa.Column('brand_value', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'brand_value')
    op.drop_column('workspaces', 'brand_kind')
    op.drop_column('users', 'avatar_value')
    op.drop_column('users', 'avatar_kind')
    # ### end Alembic commands ###
