"""file blobs table

Revision ID: 78be0f1b82c6
Revises: 9f4035e45d31
Create Date: 2026-08-22 18:18:17.792701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78be0f1b82c6'
down_revision: Union[str, Sequence[str], None] = '9f4035e45d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_blobs',
    sa.Column('key', sa.String(length=500), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_blobs_key'), 'file_blobs', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_blobs_key'), table_name='file_blobs')
    op.drop_table('file_blobs')
    # ### end Alembic commands ###
