"""invitations, presence, conversation types and participants

Revision ID: fedfe8240ff1
Revises: a69ec65aadb9
Create Date: 2026-08-22 16:49:21.042085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fedfe8240ff1'
down_revision: Union[str, Sequence[str], None] = 'a69ec65aadb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('inviter_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', 'viewer', name='invite_role'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'cancelled', name='invitation_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'email')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_workspace_id'), 'invitations', ['workspace_id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id')
    )
    op.create_index(op.f('ix_conversation_participants_conversation_id'), 'conversation_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_user_id'), 'conversation_participants', ['user_id'], unique=False)
    op.execute(
        "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'conversation_type') THEN CREATE TYPE conversation_type AS ENUM ('docs_qa', 'direct', 'group'); END IF; END $$;"
    )
    op.add_column('conversations', sa.Column('type', sa.Enum('docs_qa', 'direct', 'group', name='conversation_type'), nullable=False, server_default='docs_qa'))
    op.execute("UPDATE conversations SET type = 'docs_qa' WHERE type IS NULL")
    op.add_column('messages', sa.Column('sender_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'sender_id')
    op.drop_column('conversations', 'type')
    sa.Enum(name='conversation_type').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_conversation_participants_user_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_conversation_id'), table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index(op.f('ix_invitations_workspace_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###


